### ISSUE TITLE
API docstring formatting looks weird

### ISSUE THREAD

**Issue by pllim** [spacetelescope/stdatamodels#130]
https://stdatamodels.readthedocs.io/en/latest/api/stdatamodels.asdf_in_fits.write.html#stdatamodels.asdf_in_fits.write

The stuff in parameters run into each other.

**Comment by braingram** [comment]
Thanks for pointing that out. It appears to be widespread:
https://stdatamodels.readthedocs.io/en/latest/api/stdatamodels.jwst.datamodels.open.html#stdatamodels.jwst.datamodels.open
Perhaps this is a sphinx configuration or template issue.

Do you have any experience with this and tips on how to debug it?

**Comment by pllim** [comment]
Looks like you are using some custom STScI theme and CSS, in combination of other stuff like numpydoc and automodapi.

https://github.com/spacetelescope/stdatamodels/blob/5e4c14fbfcacc7e4b817fff12e8e58377ae7a44b/docs/source/conf.py#L14

I don't know how well they all play together. You'll have to maybe disable the STScI stuff and see if things look better, and go from there. Good luck!

**Comment by braingram** [comment]
Fixed in: https://github.com/spacetelescope/stdatamodels/pull/255
