### ISSUE TITLE
BUG: asdf_in_fits.open cannot accept HDUList (stdatamodels v1.1.0)

### ISSUE THREAD

**Issue by pllim** [spacetelescope/stdatamodels#135]
Good ol' `AsdfInFits.open` was able to accept `astropy.io.fits.HDUList` and parse the contents properly. However, using what I thought is equivalent, `asdf_in_fits.open`, in `stdatamodels` v1.1.0, I get an error. This breaks backward compatibility and blocks:

* https://github.com/spacetelescope/jdaviz/pull/2052

Minimally reproducible example (adapted from Jdaviz regression test):

```python
from astropy.io import fits
from astropy.utils.data import download_file
from stdatamodels import asdf_in_fits

jwst_asdf_url_1 = 'https://data.science.stsci.edu/redirect/JWST/jwst-data_analysis_tools/imviz_test_data/jw00042001001_01101_00001_nrcb5_cal.fits'
filename = download_file(jwst_asdf_url_1, cache=True, timeout=100)

pf = fits.open(filename)
af = asdf_in_fits.open(pf)  # Error (see below)

# But this works
from asdf.fits_embed import AsdfInFits
af2 = AsdfInFits.open(pf)  # Works
```

```
File stdatamodels/asdf_in_fits.py:52, in open(filename, **kwargs)
     33 def open(filename, **kwargs):
     34     """Read ASDF data embedded in a fits file
     35
     36     Parameters
   (...)
     49         fits file.
     50     """
---> 52     hdulist = fits.open(filename)
     53     if 'ignore_missing_extensions' not in kwargs:
     54         kwargs['ignore_missing_extensions'] = False

(This gets into io.fits internals and then io module internals.)

TypeError: stat: path should be string, bytes, os.PathLike or integer, not method
```

I don't think you should ask FITS to open something that is already a FITS object.

https://github.com/spacetelescope/stdatamodels/blob/5e4c14fbfcacc7e4b817fff12e8e58377ae7a44b/src/stdatamodels/asdf_in_fits.py#L52

William asked me to cc @braingram

**Comment by pllim** [comment]
I am also not sure about this if HDUList is provided by the user, but whatever that is consistent with `asdf.fits_embed` old behavior is good enough?

https://github.com/spacetelescope/stdatamodels/blob/5e4c14fbfcacc7e4b817fff12e8e58377ae7a44b/src/stdatamodels/asdf_in_fits.py#L64

**Comment by braingram** [comment]
Thanks for the detailed issue.

Do the changes in #136 address your needs?

**Comment by pllim** [comment]
Let's merge #136 and then I can have my Jdaviz PR pull the dev version of stdatamodels. If I pull your fork's branch, the version is gonna get messed up and that messes with dep version resolution in pip.
