### ISSUE TITLE
Allow customization of meta.date

### ISSUE THREAD

**Issue by eslavich** [spacetelescope/stdatamodels#23]
romancal schemas require an astropy.time.Time object in meta.date, but `DataModel` sets a string on initialization and on save.  We'll need to provide a way to customize that -- maybe another hook, like `on_save`, but for properties set on init.

**Comment by jdavies-st** [comment]
`meta.date` is not used by CRDS as far as I know.  `meta.observation.date` and `meta.observation.time` are the relevant keywords, and these already allow datetime objects to be assigned, but are serialized by strings via the pre-write hook.

It would be nice to keep these in sync between `jwst` and `romancal`.

**Comment by PaulHuwe** [comment]
meta.date & meta.useafter are linked to reference files in Roman and are now astropy.time.Time objects. Reference files have no observation date/time, so those can't be use as alternatives.

**Comment by jdavies-st** [comment]
Ah, these are for reference files.  Carry on.  =)

**Comment by braingram** [comment]
I'm closing this as the motivation was for roman datamodels which are now in a distinct package: https://github.com/spacetelescope/roman_datamodels that doesn't depend on stdatamodels.
