### ISSUE TITLE
ASDF files are not validated when DataModel is initialized

### ISSUE THREAD

**Issue by eslavich** [spacetelescope/stdatamodels#5]
When initializing `DataModel` with another DataModel or an HDUList, the validator runs and emits warnings if any of the content fails the new model's validation.  This does not occur when the model is initialized with an AsdfFile.

**Comment by PaulHuwe** [comment]
We need file validation for schema / file tests in romancal. Is this going to be address in the near-term?

**Comment by PaulHuwe** [comment]
We are working around this my manually invoking model.validate().
