### ISSUE TITLE
Cookiecutter templates for extension projects?

### ISSUE THREAD

**Issue by eslavich** [spacetelescope/stdatamodels#67]
There are a lot of moving parts in an ASDF extension repo, so it might be helpful to provide [cookiecutter](https://cookiecutter.readthedocs.io/) templates for a few common types of extensions.  Say, one for a repo that only provides schemas, one for new tagged objects, one for a new compressor.

**Comment by braingram** [comment]
I think this was meant for asdf :)

Also it seems addressed (at least it was) by: https://github.com/asdf-format/schemas-package-template

That template may need updating so please feel free to open an issue there if it seems out-of-date.
