### ISSUE TITLE
JSON Schema required property ignored during validation

### ISSUE THREAD

**Issue by eslavich** [spacetelescope/stdatamodels#7]
We support a property called `fits_required`, but the built-in JSON Schema `required` property seems to be ignored.

**Comment by PaulHuwe** [comment]
`required` also seems to be ignored when in a file included via `$ref.`

E.g.
core.schema
```
...
required [telescope]
...

```
referencefile.schema
```
...
- $ref: core.schema
...
```

A referencefile model will not properly validate the "telescope" keyword as required (whereas a core model will).

**Comment by braingram** [comment]
I don't believe this is a problem any more.

Testing with current main:
https://github.com/spacetelescope/stdatamodels/commit/56fdcfd469e252f71f6a688305d680a8c99887f5

The oifits schema contains many `required` keywords and is referenced by the `amioi` schema. Creating an invalid (empty `AmiOIModel` and calling `validate` produces the expected warnings from failed validation:
```python
>> import stdatamodels.jwst.datamodels as dm
>> m = dm.AmiOIModel()
>> m.validate()
...
ValidationWarning: While validating <AmiOIModel> the following error occurred:
'pi_name' is a required property
```
The `required` works for reference files via `$ref`s as well. If I modify `referencefile.schema` to require `origin` I see
```python
>> m = dm.FlatModel()
>> m.validate()
...
ValidationWarning: While validating <FlatModel(0, 0)> the following error occurred:
'origin' is a required property
```
